### ISSUE TITLE
How to get apiKey and apiSecret

### ISSUE THREAD

**Issue by krazylearner** [GBSEcom/pjsv2_example#1]
Hi
Can you explain where to register to get payment.js apiKey and  apiSecret ? I have firstdata merchant account but I think this does not solve my problem.

Thanks

```

  pjs2: {
    uat: {
      // PaymentJS apiKey
      apiKey: '',

      // PaymentJS apiSecret
      apiSecret: '',
    },
    prod: {
      apiKey: '',
      apiSecret: '',
    }
  },
```

**Comment by brandon-garcia** [comment]
Please submit a request to:
https://docs.firstdata.com/req/paymentjs
