### ISSUE TITLE
exception on submit

### ISSUE THREAD

**Issue by pthomson** [GBSEcom/pjsv2_example#2]
updated env.js config file and followed the startup instruction but when I click submit I get an exception (two actually)
![image](https://user-images.githubusercontent.com/2945852/59881846-6ced9400-9365-11e9-8ae8-1733e7ecd9ac.png)

**Comment by pthomson** [comment]
it appears it is expected behavior that the pjsv2 app would throw a 500 internal server error when the webhook URL is not configured on the Payeezy server side. The initial auth was actually successful, but the subsequent tokenize request was not because there is no webhook url for the request to send the response to. Unfortunately it is not currently a setting that the developer can set on their own account, they must wait for "support" to add it.

**Comment by BrentWMiller** [comment]
Is this still something support has to add? There's a webhook field on Payeezy, but I still get the same error.

**Comment by pthomson** [comment]
It has been several years since I implemented paymentJS for our environment, but as I recall, even though there is a place to put webhook URL, that simply does not work. I had to call their support and give them the full URL endpoint and request that they add it on their side. it was a tedious process. you have to submit their request form. Its in the "Registering with the Service" portion of their documentation.
https://docs.paymentjs.firstdata.com/#registration
https://docs.firstdata.com/req/paymentjs

**Comment by BrentWMiller** [comment]
Appreciate the help. I'll reach out to their support then, thanks!

**Comment by BrentWMiller** [comment]
Confirmed that there is 2 separate webhooks. Here's the response from support:

> The webhook URL field in the UI is for a different integration (partner reporting API) and is not related to tokenization. In fact, this is only used for ISO partners and not for merchants. So, for you, that field can be left blank. The webhook URL at the registration link is the one you would be using and it is for tokenization purposes only.
