### ISSUE TITLE
"faultstring" unresolved variable error

### ISSUE THREAD

**Issue by teapejon** [GBSEcom/pjsv2_example#3]
I am receiving and error from the boilerplate.

{"fault":{"faultstring":"Unresolved variable : verifyapikey.security-VerifyAPIKey.webhook","detail":{"errorcode":"entities.UnresolvedVariable"}}}

**Comment by brandon-garcia** [comment]
please submit a request to:
https://docs.firstdata.com/req/paymentjs

That particular error is due to a webhook not being configured.
