### ISSUE TITLE
Focus within iFrame

### ISSUE THREAD

**Issue by alexanderhrobertson** [GBSEcom/pjsv2_example#4]
Hi,

How did you focus on the field within the iFrame when tabbing from Company Name to Card Holder Name?   We cannot reproduce that in our implementation.  The user experience requires another click on Card Holder Name to focus on the field.

Thanks,
Alex

**Comment by brandon-garcia** [comment]
I believe if the body element gets focus it redirects focus to the iframe input field

**Comment by brandon-garcia** [comment]
this is implemented on the client library side
